function Hd = lp_7x_64M_64coef
%LP_7X_64M_64COEF Returns a multirate filter object.
%
% M-File generated by MATLAB(R) 7.3 and the Signal Processing Toolbox 6.6.
% Generated on: 07-Oct-2009 17:52:49
% FIR Window Lowpass filter designed using the FIR1 function.
% All frequency values are in MHz.

Fs   = 64;       % Sampling Frequency
N    = 64;       % Order
Fc   = 4.3;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

intf = 7;                     % Interpolation Factor
num  = get(Hd, 'Numerator');  % Get the numerator from the current filter.

fid1=fopen('lp_7x_64M_64coef.dat','w');
fprintf(fid1,'%1.4f, \n', num);
fclose(fid1);

Hd  = mfilt.firinterp(intf, num);




% [EOF]
