# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     debug
#     debug_clean

# Define ADI_DSP if it is not already defined.  Define this variable if you
# wish to run this Makefile on a host other than the host that created
# it and VisualDSP++ may be installed in a different directory.

ifndef ADI_DSP
ADI_DSP=C:\Program Files\Analog Devices\VisualDSP
endif

# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

# Define the command to use to delete files (which is different on Win95/98
# and Windows NT/2000)

ifeq ($(OS),Windows_NT)
RM=cmd /C del /F /Q
else
RM=command /C del
endif

#
# Begin "debug" configuration
#

ifeq ($(MAKECMDGOALS),debug)

debug : ./dma_test.dxe 

./debug/extint.doj : ./extint.c $(VDSP)/211xx/include/def21160.h $(VDSP)/211xx/include/21060.h $(VDSP)/211xx/include/signal.h extint.h 
	$(VDSP)/cc21k -c .\extint.c  -g -21160rev0 -I C:\Hammerhead\ Tools\Examples\libs\PCI -21160  -o .\debug\extint.doj  -MM

./debug/dma_test.doj : ./dma_test.c $(VDSP)/211xx/include/def21160.h $(VDSP)/211xx/include/21160.h $(VDSP)/211xx/include/signal.h $(VDSP)/211xx/include/macros.h extint.h 
	$(VDSP)/cc21k -c .\dma_test.c  -g -21160rev0 -I C:\Hammerhead\ Tools\Examples\libs\PCI -21160  -o .\debug\dma_test.doj  -MM

./dma_test.dxe : ./debug/extint.doj c:/hammerhead\ tools/examples/libs/utils/util_lib.dlb ./debug/dma_test.doj 
	$(VDSP)/cc21k.exe .\debug\extint.doj -flags-link C:\Hammerhead\ Tools\Examples\libs\UTILS\UTIL_LIB.dlb .\debug\dma_test.doj -21160 -L .\debug -o .\dma_test.dxe -MM

endif

ifeq ($(MAKECMDGOALS),debug_clean)

debug_clean:
	$(RM) ".\debug\extint.doj"
	$(RM) ".\debug\dma_test.doj"
	$(RM) ".\dma_test.dxe"

endif


