# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     debug
#     debug_clean

# Define ADI_DSP if it is not already defined.  Define this variable if you
# wish to run this Makefile on a host other than the host that created
# it and VisualDSP++ may be installed in a different directory.

ifndef ADI_DSP
ADI_DSP=C:\Program Files\Analog Devices\VisualDSP
endif

# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

# Define the command to use to delete files (which is different on Win95/98
# and Windows NT/2000)

ifeq ($(OS),Windows_NT)
RM=cmd /C del /F /Q
else
RM=command /C del
endif

#
# Begin "debug" configuration
#

ifeq ($(MAKECMDGOALS),debug)

debug : ./bd2bd_slav.dxe 

./debug/linkdma2.doj : ./linkdma2.c $(VDSP)/211xx/include/def21160.h $(VDSP)/211xx/include/21160.h $(VDSP)/211xx/include/signal.h $(VDSP)/211xx/include/macros.h linkdma.h sharc_fin.h 
	$(VDSP)/cc21k -c .\linkdma2.c  -g -21160rev0 -21160  -o .\debug\linkdma2.doj  -MM

./debug/linkbd2bdtest.doj : ./linkbd2bdtest.c $(VDSP)/211xx/include/def21160.h $(VDSP)/211xx/include/sysreg.h $(VDSP)/211xx/include/21160.h $(VDSP)/211xx/include/signal.h $(VDSP)/211xx/include/macros.h linkdma.h sharc_fin.h 
	$(VDSP)/cc21k -c .\linkBd2BdTest.c  -g -21160rev0 -21160  -o .\debug\linkBd2BdTest.doj  -MM

./bd2bd_slav.dxe : ./link21160.ldf ./debug/linkbd2bdtest.doj ./debug/linkdma2.doj $(VDSP)/211xx/lib/160_hdr.doj $(VDSP)/211xx/lib/lib160.dlb $(VDSP)/211xx/lib/libc160.dlb $(VDSP)/211xx/lib/libdsp160.dlb $(VDSP)/211xx/lib/libio160_32.dlb 
	$(VDSP)/cc21k.exe .\debug\linkdma2.doj .\debug\linkBd2BdTest.doj -T .\Link21160.ldf -21160 -L .\debug -o .\bd2bd_slav.dxe -flags-link -MM

endif

ifeq ($(MAKECMDGOALS),debug_clean)

debug_clean:
	$(RM) ".\debug\linkdma2.doj"
	$(RM) ".\debug\linkBd2BdTest.doj"
	$(RM) ".\bd2bd_slav.dxe"

endif


